name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: npm install -g supabase@latest

      - name: Link to Supabase Project
        run: supabase link --project-ref $SUPABASE_PROJECT_REF

      - name: Deploy Edge Functions
        run: |
          supabase functions deploy create-file-api
          supabase functions deploy stripe-create-product-price
          supabase functions deploy stripe-create-checkout
          supabase functions deploy stripe-webhook
